=== prohner/TransactionalEmails/sample_data_2015-05-18/CDMCustomerNotification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by ï»¿Simona (Interworks) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cus="http://www.guitarcenter.com/schemas/CDM/CDMCustomerNotification" targetNamespace="http://www.guitarcenter.com/schemas/CDM/CDMCustomerNotification" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<xs:element name="EmailNotification">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="NotificationType" type="xs:string"/>
				<xs:element name="NotificationTrackingID" type="xs:string"/>
				<xs:element name="EmailTo" type="xs:string"/>
				<xs:element name="EmailSubject" type="xs:string"/>
				<xs:element name="ReceipientName" type="xs:string"  minOccurs="0" />
				<xs:choice>
					<xs:element ref="cus:AbandonedCartNotification"/>
					<xs:element ref="cus:AccountConfirmNotification"/>
					<xs:element ref="cus:PasswordResetNotification"/>
					<xs:element ref="cus:PasswordResetConfirmNotification"/>
					<xs:element ref="cus:WishlistNotification"/>
					<xs:element ref="cus:AlertNotification"/>
					<xs:element ref="cus:EmailForPriceNotification"/>
					<xs:element ref="cus:TellYourFriendNotification"/>
					<xs:element ref="cus:QuoteNotification"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="EnterpriseSkuID" type="xs:string"/>
			<xs:element name="ProductName" type="xs:string"/>
			<xs:element name="ProductDescription" type="xs:string"/>
			<xs:element name="ProductURL" type="xs:string" minOccurs="0"/>
			<xs:element name="ProductImageURL" type="xs:string" minOccurs="0"/>
			<xs:element name="ItemTransactionDetails" type="cus:ItemTransactionType"/>
			<xs:element name="ShipDate" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="UnitPrice" type="xs:decimal" minOccurs="0"/>
			<xs:element name="ExtPrice" type="xs:decimal" minOccurs="0"/>
			<xs:element name="ShipAndHandlingCost" type="xs:decimal" minOccurs="0"/>
			<xs:element name="Tax" type="xs:decimal" minOccurs="0"/>
			<xs:element name="MiscCharges" type="xs:decimal" minOccurs="0"/>
			<xs:element name="Discount" type="xs:decimal" minOccurs="0"/>
			<xs:element name="Promotions" type="cus:PromotionType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ItemRating" type="xs:int" minOccurs="0"/>
			<xs:sequence minOccurs="0">
				<xs:element name="TotalReviews" type="xs:int" minOccurs="0"/>
				<xs:element name="ReadReviewsURL" type="xs:string" minOccurs="0"/>
				<xs:element name="WriteReviewsURL" type="xs:string" minOccurs="0"/>
			</xs:sequence>
			<xs:element name="RecommendedAccessories" type="cus:ItemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ComponentID" type="xs:string" minOccurs="0"/>
			<xs:element name="KitMessage" type="xs:string" minOccurs="0"/>
			<xs:element name="Component" type="cus:ItemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="WarrantyComponent" type="cus:ItemType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ItemTransactionType">
		<xs:sequence>
			<xs:element name="TransactionType" type="xs:string" minOccurs="0"/>
			<xs:element name="Quantity" type="xs:int" minOccurs="0"/>
			<xs:element name="LineTotal" type="xs:int" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TransactionTotalType">
		<xs:sequence>
			<xs:element name="SubTotal" type="xs:decimal" minOccurs="0"/>
			<xs:element name="TotalShipAndHandlingCost" type="xs:decimal" minOccurs="0"/>
			<xs:element name="TotalTax" type="xs:decimal" minOccurs="0"/>
			<xs:element name="TotalMiscCharges" type="xs:decimal" minOccurs="0"/>
			<xs:element name="TotalDiscount" type="xs:decimal" minOccurs="0"/>
			<xs:element name="GroupTotal" type="xs:decimal" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PromotionType">
		<xs:sequence>
			<xs:element name="Promotion" type="xs:string" minOccurs="1"/>
			<xs:element name="PromotionDescription" type="xs:string" minOccurs="0"/>
			<xs:element name="PromotionStartDate" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="PromotionEndDate" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="DiscountAmount" type="xs:decimal" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AddressType">
		<xs:sequence>
			<xs:element name="AddressType" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="FirstName" type="xs:string" minOccurs="0"/>
			<xs:element name="LastName" type="xs:string" minOccurs="0"/>
			<xs:element name="MiddleInitial" type="xs:string" minOccurs="0"/>
			<xs:element name="CompanyName" type="xs:string" minOccurs="0"/>
			<xs:element name="AddressLine1" type="xs:string" minOccurs="0"/>
			<xs:element name="AddressLine2" type="xs:string" minOccurs="0"/>
			<xs:element name="AddressLine3" type="xs:string" minOccurs="0"/>
			<xs:element name="AddressLine4" type="xs:string" minOccurs="0"/>
			<xs:element name="City" type="xs:string" minOccurs="0"/>
			<xs:element name="State" type="xs:string" minOccurs="0"/>
			<xs:element name="CountryCode" type="xs:string" minOccurs="0"/>
			<xs:element name="CountryName" type="xs:string" minOccurs="0"/>
			<xs:element name="PostalCode" type="xs:string" minOccurs="0"/>
			<xs:element name="TelephoneNumber" type="cus:PhoneType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="EMailAddress" type="cus:EmailType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EmailType">
		<xs:sequence>
			<xs:element name="Type" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Email" type="xs:string" minOccurs="1"/>
			<xs:element name="isPrimary" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PhoneType">
		<xs:sequence>
			<xs:element name="Type" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Phone" type="xs:string" minOccurs="0"/>
			<xs:element name="isPrimary" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CustomerDataType">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string" minOccurs="0"/>
			<xs:element name="LastName" type="xs:string" minOccurs="0"/>
			<xs:element name="MiddleName" type="xs:string" minOccurs="0"/>
			<xs:element name="Birthday" type="xs:date" minOccurs="0"/>
			<xs:element name="LoyaltyMemberNumber" type="xs:string" minOccurs="0"/>
			<xs:element name="CustomerID" type="xs:string" minOccurs="0"/>
			<xs:element name="CustomerPO" type="xs:string" minOccurs="0"/>
			<xs:element name="TaxExemptID" type="xs:string" minOccurs="0"/>
			<xs:element name="CustomerCreationDate" type="xs:string" minOccurs="0"/>
			<xs:element name="Preference" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="name" type="xs:string"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ContactAddress" type="cus:AddressType" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="BrandType">
		<xs:sequence>
			<xs:element name="BrandLogoURL" type="xs:string" minOccurs="0"/>
			<xs:element name="BrandName" type="xs:string" minOccurs="0"/>
			<xs:element name="BrandURL" type="xs:string" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="brandID" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="baseCustomerNotification">
		<xs:sequence>
			<xs:element name="CustomerSource">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ChannelID" type="xs:string"/>
						<xs:element name="Brand" type="cus:BrandType"/>
						<xs:element name="SiteID" type="xs:string" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="CustomerContact">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Customer" type="cus:CustomerDataType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="AbandonedCartNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="DefaultCurrency" type="xs:string" minOccurs="1"/>
						<xs:element name="ShoppingCartItems" type="cus:ItemType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="CartTotal" type="cus:TransactionTotalType"/>
						<xs:element name="CartUrl" type="xs:string" minOccurs="1"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AccountConfirmNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PasswordResetNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="PasswordResetURL" type="xs:string"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PasswordResetConfirmNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="WishlistNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="DefaultCurrency" type="xs:string" minOccurs="1"/>
						<xs:element name="WishListItems" type="cus:ItemType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="WishListTotal" type="cus:TransactionTotalType" minOccurs="0"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AlertNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="DefaultCurrency" type="xs:string" minOccurs="1"/>
						<xs:element name="InStockItems" type="cus:ItemType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="InStockTotal" type="cus:TransactionTotalType"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="EmailForPriceNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="DefaultCurrency" type="xs:string" minOccurs="1"/>
						<xs:element name="PriceOfItems" type="cus:ItemType" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="TellYourFriendNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="DefaultCurrency" type="xs:string" minOccurs="1"/>
						<xs:element name="RecentlyPurchasedItems" type="cus:ItemType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="PurchaseTotal" type="cus:TransactionTotalType"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="QuoteNotification">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="cus:baseCustomerNotification">
					<xs:sequence>
						<xs:element name="DefaultCurrency" type="xs:string" minOccurs="1"/>
						<xs:element name="ShoppingCartItems" type="cus:ItemType" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="CartTotal" type="cus:TransactionTotalType"/>
						<xs:element name="AddCartToUrl" type="xs:string" minOccurs="1"/>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== prohner/TransactionalEmails/sample_data_2015-03-23/archive/PasswordResetConfirmNotification.xml
<?xml version="1.0" encoding="UTF-8"?>
<cus:EmailNotification xmlns:cus="http://www.guitarcenter.com/schemas/CDM/CDMCustomerNotification"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.guitarcenter.com/schemas/CDM/CDMCustomerNotification file:/Users/rajanikanth.rachakat/Documents/vmsystem/CDMCustomerNotification.xsd">
    <NotificationType>NotificationType0</NotificationType>
    <NotificationTrackingID>NotificationTrackingID0</NotificationTrackingID>
    <EmailTo>EmailTo0</EmailTo>
    <EmailSubject>EmailSubject0</EmailSubject>
    <cus:PasswordResetConfirmNotification>
        <CustomerSource>
            <ChannelID>ChannelID0</ChannelID>
            <Brand brandID="GC.com">
                <BrandLogoURL>BrandLogoURL0</BrandLogoURL>
                <BrandName>Guitar Center</BrandName>
                <BrandURL>BrandURL0</BrandURL>
            </Brand>
            <SiteID>SiteID0</SiteID>
        </CustomerSource>
        <CustomerContact>
            <Customer>
                <FirstName>FirstName0</FirstName>
                <LastName>LastName0</LastName>
                <MiddleName>MiddleName0</MiddleName>
                <Birthday>2006-05-04</Birthday>
                <LoyaltyMemberNumber>LoyaltyMemberNumber0</LoyaltyMemberNumber>
                <CustomerID>CustomerID0</CustomerID>
                <CustomerPO>CustomerPO0</CustomerPO>
                <TaxExemptID>TaxExemptID0</TaxExemptID>
                <CustomerCreationDate>CustomerCreationDate0</CustomerCreationDate>
                <Preference name="name0">Preference0</Preference>
                <Preference name="name1">Preference1</Preference>
                <ContactAddress>
                    <AddressType>AddressType0</AddressType>
                    <AddressType>AddressType1</AddressType>
                    <FirstName>FirstName1</FirstName>
                    <LastName>LastName1</LastName>
                    <MiddleInitial>MiddleInitial0</MiddleInitial>
                    <CompanyName>CompanyName0</CompanyName>
                    <AddressLine1>AddressLine10</AddressLine1>
                    <AddressLine2>AddressLine20</AddressLine2>
                    <AddressLine3>AddressLine30</AddressLine3>
                    <AddressLine4>AddressLine40</AddressLine4>
                    <City>City0</City>
                    <State>State0</State>
                    <CountryCode>CountryCode0</CountryCode>
                    <CountryName>CountryName0</CountryName>
                    <PostalCode>PostalCode0</PostalCode>
                    <TelephoneNumber>
                        <isPrimary>false</isPrimary>
                    </TelephoneNumber>
                    <TelephoneNumber>
                        <isPrimary>false</isPrimary>
                    </TelephoneNumber>
                    <EMailAddress>
                        <Email>Email0</Email>
                        <isPrimary>false</isPrimary>
                    </EMailAddress>
                    <EMailAddress>
                        <Email>Email1</Email>
                        <isPrimary>false</isPrimary>
                    </EMailAddress>
                </ContactAddress>
            </Customer>
        </CustomerContact>
    </cus:PasswordResetConfirmNotification>
</cus:EmailNotification>

=== prohner/TransactionalEmails/sample_data_2015-03-23/instance5.xml
<?xml version="1.0" encoding="UTF-8"?>
<cus:EmailNotification xmlns:cus="http://www.guitarcenter.com/schemas/CDM/CDMCustomerNotification"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.guitarcenter.com/schemas/CDM/CDMCustomerNotification file:/Users/rajanikanth.rachakat/Documents/vmsystem/CDMCustomerNotification.xsd">
    <NotificationType>NotificationType0</NotificationType>
    <NotificationTrackingID>NotificationTrackingID0</NotificationTrackingID>
    <EmailTo>EmailTo0</EmailTo>
    <EmailSubject>EmailSubject0</EmailSubject>
    <cus:EmailForPriceNotification>
        <CustomerSource>
            <ChannelID>ChannelID0</ChannelID>
            <Brand brandID="brandID0">
                <BrandLogoURL>BrandLogoURL0</BrandLogoURL>
                <BrandName>BrandName0</BrandName>
                <BrandURL>BrandURL0</BrandURL>
            </Brand>
            <SiteID>SiteID0</SiteID>
        </CustomerSource>
        <CustomerContact>
            <Customer>
                <FirstName>FirstName0</FirstName>
                <LastName>LastName0</LastName>
                <MiddleName>MiddleName0</MiddleName>
                <Birthday>2006-05-04</Birthday>
                <LoyaltyMemberNumber>LoyaltyMemberNumber0</LoyaltyMemberNumber>
                <CustomerID>CustomerID0</CustomerID>
                <CustomerPO>CustomerPO0</CustomerPO>
                <TaxExemptID>TaxExemptID0</TaxExemptID>
                <CustomerCreationDate>CustomerCreationDate0</CustomerCreationDate>
                <Preference name="name0">Preference0</Preference>
                <Preference name="name1">Preference1</Preference>
                <ContactAddress>
                    <AddressType>AddressType0</AddressType>
                    <AddressType>AddressType1</AddressType>
                    <FirstName>FirstName1</FirstName>
                    <LastName>LastName1</LastName>
                    <MiddleInitial>MiddleInitial0</MiddleInitial>
                    <CompanyName>CompanyName0</CompanyName>
                    <AddressLine1>AddressLine10</AddressLine1>
                    <AddressLine2>AddressLine20</AddressLine2>
                    <AddressLine3>AddressLine30</AddressLine3>
                    <AddressLine4>AddressLine40</AddressLine4>
                    <City>City0</City>
                    <State>State0</State>
                    <CountryCode>CountryCode0</CountryCode>
                    <CountryName>CountryName0</CountryName>
                    <PostalCode>PostalCode0</PostalCode>
                    <TelephoneNumber>
                        <isPrimary>false</isPrimary>
                    </TelephoneNumber>
                    <TelephoneNumber>
                        <isPrimary>false</isPrimary>
                    </TelephoneNumber>
                    <EMailAddress>
                        <Email>Email0</Email>
                        <isPrimary>false</isPrimary>
                    </EMailAddress>
                    <EMailAddress>
                        <Email>Email1</Email>
                        <isPrimary>false</isPrimary>
                    </EMailAddress>
                </ContactAddress>
            </Customer>
        </CustomerContact>
        <DefaultCurrency>DefaultCurrency0</DefaultCurrency>
        <PriceOfItems>
            <EnterpriseSkuID>EnterpriseSkuID0</EnterpriseSkuID>
            <ProductName>ProductName0</ProductName>
            <ProductDescription>ProductDescription0</ProductDescription>
            <ProductURL>ProductURL0</ProductURL>
            <ProductImageURL>ProductImageURL0</ProductImageURL>
            <ItemTransactionDetails>
                <TransactionType>TransactionType0</TransactionType>
                <Quantity>Quantity0</Quantity>
                <LineTotal>0</LineTotal>
            </ItemTransactionDetails>
            <ShipDate>2006-05-04T18:13:51.0</ShipDate>
            <UnitPrice>0</UnitPrice>
            <ExtPrice>0</ExtPrice>
            <ShipAndHandlingCost>0</ShipAndHandlingCost>
            <Tax>0</Tax>
            <MiscCharges>0</MiscCharges>
            <Discount>0</Discount>
            <Promotions>
                <Promotion>Promotion0</Promotion>
                <PromotionDescription>PromotionDescription0</PromotionDescription>
                <PromotionStartDate>2006-05-04T18:13:51.0</PromotionStartDate>
                <PromotionEndDate>2006-05-04T18:13:51.0</PromotionEndDate>
                <DiscountAmount>0</DiscountAmount>
            </Promotions>
            <Promotions>
                <Promotion>Promotion1</Promotion>
                <PromotionDescription>PromotionDescription1</PromotionDescription>
                <PromotionStartDate>2006-05-04T18:13:51.0</PromotionStartDate>
                <PromotionEndDate>2006-05-04T18:13:51.0</PromotionEndDate>
                <DiscountAmount>0</DiscountAmount>
            </Promotions>
            <ItemRating>ItemRating0</ItemRating>
            <TotalReviews>TotalReviews0</TotalReviews>
            <ReadReviewsURL>ReadReviewsURL0</ReadReviewsURL>
            <WriteReviewsURL>WriteReviewsURL0</WriteReviewsURL>
            <ComponentID>ComponentID0</ComponentID>
            <KitMessage>KitMessage0</KitMessage>
        </PriceOfItems>
        <PriceOfItems>
            <EnterpriseSkuID>EnterpriseSkuID1</EnterpriseSkuID>
            <ProductName>ProductName1</ProductName>
            <ProductDescription>ProductDescription1</ProductDescription>
            <ProductURL>ProductURL1</ProductURL>
            <ProductImageURL>ProductImageURL1</ProductImageURL>
            <ItemTransactionDetails>
                <TransactionType>TransactionType1</TransactionType>
                <Quantity>Quantity1</Quantity>
                <LineTotal>0</LineTotal>
            </ItemTransactionDetails>
            <ShipDate>2006-05-04T18:13:51.0</ShipDate>
            <UnitPrice>0</UnitPrice>
            <ExtPrice>0</ExtPrice>
            <ShipAndHandlingCost>0</ShipAndHandlingCost>
            <Tax>0</Tax>
            <MiscCharges>0</MiscCharges>
            <Discount>0</Discount>
            <Promotions>
                <Promotion>Promotion2</Promotion>
                <PromotionDescription>PromotionDescription2</PromotionDescription>
                <PromotionStartDate>2006-05-04T18:13:51.0</PromotionStartDate>
                <PromotionEndDate>2006-05-04T18:13:51.0</PromotionEndDate>
                <DiscountAmount>0</DiscountAmount>
            </Promotions>
            <Promotions>
                <Promotion>Promotion3</Promotion>
                <PromotionDescription>PromotionDescription3</PromotionDescription>
                <PromotionStartDate>2006-05-04T18:13:51.0</PromotionStartDate>
                <PromotionEndDate>2006-05-04T18:13:51.0</PromotionEndDate>
                <DiscountAmount>0</DiscountAmount>
            </Promotions>
            <ItemRating>ItemRating1</ItemRating>
            <TotalReviews>TotalReviews1</TotalReviews>
            <ReadReviewsURL>ReadReviewsURL1</ReadReviewsURL>
            <WriteReviewsURL>WriteReviewsURL1</WriteReviewsURL>
            <ComponentID>ComponentID1</ComponentID>
            <KitMessage>KitMessage1</KitMessage>
        </PriceOfItems>
        <PriceTotal>
            <SubTotal>0</SubTotal>
            <TotalShipAndHandlingCost>0</TotalShipAndHandlingCost>
            <TotalTax>0</TotalTax>
            <TotalMiscCharges>0</TotalMiscCharges>
            <TotalDiscount>0</TotalDiscount>
            <GroupTotal>0</GroupTotal>
        </PriceTotal>
    </cus:EmailForPriceNotification>
</cus:EmailNotification>
